version: "3.3"

services:
  db:
    image: postgres:13
    container_name: store_db
    restart: always
    env_file:
      - project.env
    volumes:
      - .pgdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: store_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  .pgdata:
